kumuluzee:
  name: fs-task
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8080
  discovery:
    etcd:
      hosts: http://192.168.2.162:2379
    ttl: 20
    ping-interval: 15